# Maki Dice (Linux)
# github.com/andrewmichaelpowell

name: makidice
description: Dice for role-playing games
publish_to: 'none'
version: 1.9.3+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/icon.png
  uses-material-design: true
